// Builds the topic-wise table of contents (content/toc.json): for every chapter with MCQs,
// each item of every section is placed under one of the chapter's topics.
// Run after adding or changing content:  node tools/build-toc.mjs
//
// Topics come from data/toc-rules.json or, by default, the chapter's MCQ topics in book order.
// Items already tagged with one of those topics keep it. Every other item (CQ, ক/খ with a
// coarser topic, formulas, concepts, mistakes …) goes to the topic whose MCQs it reads most
// like (TF-IDF over words and in-word 4-grams, so Bengali inflections still match). A CQ that
// reads almost equally like two topics is listed under both.
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (f) => JSON.parse(readFileSync(join(root, f), 'utf8'));
const rules = read('data/toc-rules.json');
const index = read('content/index.json').sections;
const verbose = process.argv.includes('--verbose');

const byChapter = new Map();
for (const [sid, reg] of Object.entries(index)) {
  const m = sid.match(/^(.*)_([a-z_]+?)$/);
  const data = read(reg.file);
  const chapterId = sid.slice(0, sid.lastIndexOf('_'));
  const type = sid.slice(sid.lastIndexOf('_') + 1);
  if (!m) continue;
  if (!byChapter.has(chapterId)) byChapter.set(chapterId, []);
  byChapter.get(chapterId).push({ type, items: data.items });
}

const textOf = (it) => [
  it.question, ...(it.options ?? []), it.explanation, it.answer, it.title, it.stem, it.body, it.note, it.result,
  ...(it.parts ?? []).flatMap((p) => [p.q, p.a]), ...(it.formulas ?? []), ...(it.steps ?? []),
].filter(Boolean).join(' ');

function features(text) {
  const out = new Map();
  const add = (k, w) => out.set(k, (out.get(k) ?? 0) + w);
  for (const w of String(text).toLowerCase().match(/[\p{L}\p{M}\p{N}]+/gu) ?? []) {
    if (w.length < 2) continue;
    add(`w:${w}`, 1);
    const ch = [...w];
    for (let i = 0; i + 4 <= ch.length; i++) add(`g:${ch.slice(i, i + 4).join('')}`, 0.5);
  }
  return out;
}

const out = { $comment: 'Generated by tools/build-toc.mjs — do not edit by hand.', chapters: {} };
let total = 0;
for (const [chapterId, sections] of byChapter) {
  const mcq = sections.find((s) => s.type === 'mcq');
  if (!mcq) continue;
  const cfg = rules.chapters?.[chapterId] ?? {};
  const names = cfg.topics ?? [...new Set(mcq.items.map((i) => i.topic).filter((t) => t && !rules.exclude.includes(t)))];
  if (names.length < 2) continue;
  const topics = names.map((name, i) => ({ id: `t${String(i + 1).padStart(2, '0')}`, name, items: [] }));
  const byName = new Map(topics.map((t) => [t.name, t]));
  const general = [];

  // document frequencies over every item of the chapter
  const docs = sections.flatMap((s) => s.items.map((it) => ({ it, type: s.type, f: features(`${it.topic ?? ''} ${textOf(it)}`) })));
  const df = new Map();
  for (const d of docs) for (const k of d.f.keys()) df.set(k, (df.get(k) ?? 0) + 1);
  const idf = (k) => Math.log((docs.length + 1) / ((df.get(k) ?? 0) + 1));
  const vec = (f) => {
    const v = new Map();
    let n = 0;
    for (const [k, c] of f) { const x = (1 + Math.log(c)) * idf(k); v.set(k, x); n += x * x; }
    n = Math.sqrt(n) || 1;
    for (const [k, x] of v) v.set(k, x / n);
    return v;
  };
  const cos = (a, b) => { let s = 0; for (const [k, x] of a) { const y = b.get(k); if (y) s += x * y; } return s; };

  // topic centroids from the items already tagged with a topic name
  const cent = new Map(topics.map((t) => [t, new Map()]));
  for (const d of docs) {
    const t = byName.get(d.it.topic);
    if (!t) continue;
    for (const [k, x] of vec(d.f)) cent.get(t).set(k, (cent.get(t).get(k) ?? 0) + x);
  }
  for (const [t, c] of cent) {
    let n = 0;
    for (const x of c.values()) n += x * x;
    n = Math.sqrt(n) || 1;
    for (const [k, x] of c) c.set(k, x / n);
  }

  for (const d of docs) {
    const id = d.it.id;
    total++;
    if (rules.chapterWide.includes(d.type)) { general.push(id); continue; }
    const tagged = byName.get(d.it.topic);
    if (tagged) { tagged.items.push(id); continue; }
    // the item's own (coarser) topic label counts three times
    const classify = (text) => {
      const v = vec(features(`${d.it.topic ?? ''} `.repeat(3) + text));
      return topics.map((t) => [t, cos(v, cent.get(t))]).sort((x, y) => y[1] - x[1])[0];
    };
    if (d.type === 'cq' && d.it.parts?.length) {
      // a creative question is listed under the topic of its stem and of each গ/ঘ part
      const stem = d.it.stem ?? '';
      const hard = d.it.parts.filter((p) => /গ|ঘ/.test(p.label));
      const picks = [classify(`${stem} ${d.it.parts.map((p) => p.q).join(' ')}`), ...(hard.length ? hard : d.it.parts).map((p) => classify(`${stem} ${p.q} ${p.a ?? ''}`))]
        .filter(([, sc]) => sc >= 0.04);
      const chosen = [...new Set(picks.map(([t]) => t))].slice(0, 2);
      if (!chosen.length) { general.push(id); continue; }
      chosen.forEach((t) => t.items.push(id));
      if (verbose) console.log(`${id}\t${chosen.map((t) => t.name).join(' + ')}\t${stem.slice(0, 50)}`);
      continue;
    }
    const [best, s1] = classify(textOf(d.it));
    if (s1 < 0.04) { general.push(id); continue; }
    best.items.push(id);
  }
  out.chapters[chapterId] = { topics, general };
}
writeFileSync(join(root, 'content/toc.json'), `${JSON.stringify(out)}\n`);
const chs = Object.entries(out.chapters);
console.log(`content/toc.json: ${chs.length} chapters, ${total} items`);
for (const [id, c] of chs) console.log(`  ${id}: ${c.topics.map((t) => t.items.length).join(' · ')} (+${c.general.length} chapter-wide)`);
